<span class="mini-nav"><a href="index.php/company/welcome">Empresas</a></span>
<main class="home-candidate center-of-center-full">

    <header class="header-candidate ">
        <h2>NUTRIKUCALAKALA</h2>
        <h1 class="intro">Aqui poderá se cadastrar para <br />concorrer para empregos</h1>
        <div class="button-group">
            <a class="w-100p" href="index.php/candidate/signin"><button class="bg-primary-color w-100p">Nova Candidatura </button></a>
            <a class="w-100p" href="index.php/candidate/login"><button class="bg-secondary-color w-100p"> Acompanhar Candidatura </button></a>
        </div>
    </header>
</main>
