<main class="center-of-center-full">
<fieldset class="form-fieldset">
    <i class="fal fa-times"></i>
    <legend class="form-legend">Acompanhar Candidatira</legend>
    <form method="post">
        <input type="text" name="first-name" placeholder="Nome próprio">
        <input type="text" name="last-name" placeholder="Sobrenome">
        <input type="date" name="burn-date">
        <button type="submit" class="bg-primary-color">Seguinte</button>
        <button type="reset" class="bg-secondary-color">Limpar Campos</button>
    </form>
</fieldset>
</main>
