<span class="mini-nav"><a href="index.php/company/welcome">Empresas</a></span>
<main class="home-candidate center-of-center-full">

    <header class="header-candidate ">
        <h2>NUTRIKUCALAKALA EMPRESAS</h2>
        <h1 class="intro">Aqui poderá se recrutar para <br/> preencher vagas de emprego</h1>
        <div class="button-group">
            <a class="w-100p" href="index.php/company/login"><button class="bg-primary-color w-100p">Já tenho uma conta</button></a>
            <a class="w-100p" href="index.php/company/signin"><button class="bg-secondary-color w-100p">Cadastar Empresa como nova</button></a>
        </div>
    </header>
</main>
