<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Nutrikucalakala</title>
    <meta name='viewport' content='width=device-width,initial-scale=1.0,shrink-to-fit=no' />
    <meta name='author' content='Zenith Co. +244 922 282 804' />
    <meta name='description' content='Nutrikucalakala uma forma mais fácil, ágil e dinâmica para achar obter um emprego' />
    <meta name='keywords' content='Trabalho Empregos Jobs concurso emprego Angola' />
    <link rel='icon' type='image/png' href='view/assets/img/logo.png' />
    
    <base href='http://localhost/<?=$GLOBALS['name']?>/'>
    
    <meta property='og:image' content='view/assets/img/logo.png' />
    <meta property='og:title' content='Nutrikucalakala' />
    <meta property='og:description' content='Nutrikucalakala uma forma mais fácil, ágil e dinâmica para achar obter um emprego' />
    <link rel="stylesheet" href="view/assets/css/main.css">
</head>
<body>
    